In [1]:
import requests
import pandas as pd
import time

In [2]:
def get_horse(horse_number):
    return requests.get(f'https://api.zed.run/api/v1/horses/get/{horse_number}').json()

In [3]:
def scrape_horses(start_horse_number, stop_horse_number):
    return_data = []
    for i in range(start_horse_number, stop_horse_number + 1):
        horse = get_horse(i)
        horse['id'] = i
        return_data.append(horse)
        time.sleep(5)
    return return_data

In [4]:
horses = scrape_horses(0,14999)

In [7]:
# identify the fields we care about
important_fields = [
    "id",
    "bloodline",
    "breed_type",
    "genotype",
    "hash_info.name",
    "win_rate",
    "number_of_races",
    "parents.father.bloodline",
    "parents.father.breed_type",
    "parents.father.genotype",
    "parents.father.hash_info.name",
    "parents.father.win_rate",
    "parents.father.number_of_races",
    "parents.mother.bloodline",
    "parents.mother.breed_type",
    "parents.mother.genotype",
    "parents.mother.hash_info.name",
    "parents.mother.win_rate",
    "parents.mother.number_of_races"
]

In [6]:
df = pd.json_normalize(horses)

In [8]:
df_out = df[important_fields]

In [10]:
df_out.head()

,id,bloodline,breed_type,genotype,hash_info.name,win_rate,number_of_races,parents.father.bloodline,parents.father.breed_type,parents.father.genotype,parents.father.hash_info.name,parents.father.win_rate,parents.father.number_of_races,parents.mother.bloodline,parents.mother.breed_type,parents.mother.genotype,parents.mother.hash_info.name,parents.mother.win_rate,parents.mother.number_of_races
0,15000,Buterin,genesis,Z10,Thrill Bill,100.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15001,Buterin,genesis,Z10,Smiley Face,0.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15002,Finney,genesis,Z5,Illusions,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15003,Finney,genesis,Z6,Frank Angel,0.0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15004,Finney,genesis,Z6,Penalty Kick,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_out.to_csv('horses_15000_15300.csv', index=False)